### ISSUE TITLE
String format and delimiters in .toml localization files

### ISSUE THREAD

**Issue by Patriccollu** [aclap-dev/vdhlocales#2]
Hello,

Some clarification about the format of strings used by localization files stored in [vdhlocales repository](https://github.com/aclap-dev/vdhlocales) would be very appreciated.

When checking the current versions of `en_US.toml` and `co.toml` files, we can see the presence of two different string delimiters: three simple quotes (''') or double quote (").

For example `en_US.toml` contains strings such as:
```
	GB = '''$1 GB'''
	action_bulkdownloadconvert_title = '''Bulk Download & Convert'''
	## COPIED FROM V8
	v9_coapp_required = '''Companion application required'''
	## Panel
	v9_panel_view_show_all_tabs = "Show all tabs"
```

Whereas Corsican localization, in `co.toml` file, contains:
```
	GB = "$1 Go"
	action_bulkdownloadconvert_title = "Scaricà è cunvertisce da gruppu"
	v9_coapp_required = "Appiecazione cumpagnu richiesta"
```

We can note that the same variable may have different delimiters, depending on the `.toml` file.

When updating `co.toml` file, do I need to respect the existing string delimiters or may I use always the same, for example double quote (") on ALL the strings?

Please can you clarify?

I also opened issue [#896](https://github.com/aclap-dev/video-downloadhelper/discussions/896) but I don't know if it was the right place to raise this question. If not, I will close it.

Best regards,
Patriccollu.

**Comment by paulrouget** [comment]
The format we're using is TOML strings, as specified here: https://toml.io/en/v1.0.0#string

So, you can use whatever works best for you (quotes, tripe simple quotes, …) as long as it's TOML compatible.

I usually prefer to use `'''` to avoid quotes escaping issues.

You can validate your content with this tool: https://www.toml-lint.com/

**Comment by Patriccollu** [comment]
@paulrouget
Hi Paul,

Thank you for having clarified! I also appreciate all the details provided.

I'm closing this issue, as well as [#896](https://github.com/aclap-dev/video-downloadhelper/discussions/896).

Best regards,
Patriccollu.
